# Chapter 7. Classification

* 추가할 부분

> - GLMNet 구동 원리와 사이킷런과의 차이(python, R)
> - 사이킷런에서의 Decision Tree 이용법 비교(Python, R)
> - 사이킷런에서의 KNN 이용법 비교 및 R에서의 knn 이용법 비교
> - LIBSVM 구동법 확인 및 사이킷런과 R의 e1071 사용법과의 차이 비교

In [1]:
pwd()

"C:\\Users\\user"

In [2]:
using Pkg

In [29]:
# findaccuracy 함수 설정
findaccuracy(p, r) = sum(p .== r)/length(r)

findaccuracy (generic function with 1 method)

In [3]:
using GLMNet

LoadError: ArgumentError: Package GLMnet not found in current path:
- Run `import Pkg; Pkg.add("GLMnet")` to install the GLMnet package.


In [6]:
# Pkg.add("GLMNet")

   Resolving package versions...
   Installed GLMNet ─ v0.6.1
    Updating `C:\Users\user\.julia\environments\v1.6\Project.toml`
  [8d5ece8b] + GLMNet v0.6.1
    Updating `C:\Users\user\.julia\environments\v1.6\Manifest.toml`
  [8d5ece8b] + GLMNet v0.6.1
  [78c6b45d] + glmnet_jll v5.0.0+0
Precompiling project...
  ✓ glmnet_jll
  ✓ GLMNet
2 dependencies successfully precompiled in 7 seconds (296 already precompiled)


In [4]:
using GLMNet

In [5]:
using RDatasets

In [6]:
using MLBase

In [7]:
using Plots

In [8]:
using DecisionTree

In [12]:
# Pkg.add("DecisionTree")

   Resolving package versions...
   Installed DecisionTree ─ v0.10.10
    Updating `C:\Users\user\.julia\environments\v1.6\Project.toml`
  [7806a523] + DecisionTree v0.10.10
    Updating `C:\Users\user\.julia\environments\v1.6\Manifest.toml`
  [7806a523] + DecisionTree v0.10.10
Precompiling project...
  ✓ DecisionTree
1 dependency successfully precompiled in 3 seconds (298 already precompiled)


In [9]:
using DecisionTree

In [10]:
using Distances

In [11]:
using NearestNeighbors

In [16]:
# Pkg.add("NearestNeighbors")

   Resolving package versions...
    Updating `C:\Users\user\.julia\environments\v1.6\Project.toml`
  [b8a86587] + NearestNeighbors v0.4.8
  No Changes to `C:\Users\user\.julia\environments\v1.6\Manifest.toml`


In [17]:
using NearestNeighbors

In [12]:
using Random

In [13]:
using LinearAlgebra

In [14]:
using DataStructures

In [21]:
# Pkg.add("DataStructures")

   Resolving package versions...
    Updating `C:\Users\user\.julia\environments\v1.6\Project.toml`
  [864edb3b] + DataStructures v0.18.9
  No Changes to `C:\Users\user\.julia\environments\v1.6\Manifest.toml`


In [22]:
using DataStructures

In [15]:
using LIBSVM

In [24]:
# Pkg.add("LIBSVM")

   Resolving package versions...
   Installed libsvm_jll ──── v3.24.0+1
   Installed liblinear_jll ─ v2.30.0+0
   Installed LIBSVM ──────── v0.6.0
   Installed LIBLINEAR ───── v0.6.0
    Updating `C:\Users\user\.julia\environments\v1.6\Project.toml`
  [b1bec4e5] + LIBSVM v0.6.0
    Updating `C:\Users\user\.julia\environments\v1.6\Manifest.toml`
  [2d691ee1] + LIBLINEAR v0.6.0
  [b1bec4e5] + LIBSVM v0.6.0
  [275f1f90] + liblinear_jll v2.30.0+0
  [08558c22] + libsvm_jll v3.24.0+1
Precompiling project...
  ✓ libsvm_jll
  ✓ liblinear_jll
  ✓ LIBLINEAR
  ✓ LIBSVM
4 dependencies successfully precompiled in 4 seconds (299 already precompiled)


In [25]:
using LIBSVM

In [1]:
using Pkg
using GLMNet
using RDatasets
using MLBase
using Plots
using DecisionTree
using Distances
using NearestNeighbors
using Random
using LinearAlgebra
using DataStructures
using LIBSVM

In [16]:
iris = dataset("datasets", "iris")

150×5 DataFrame
 Row │ SepalLength  SepalWidth  PetalLength  PetalWidth  Species   
     │ Float64      Float64     Float64      Float64     Cat…      
─────┼─────────────────────────────────────────────────────────────
   1 │         5.1         3.5          1.4         0.2  setosa
   2 │         4.9         3.0          1.4         0.2  setosa
   3 │         4.7         3.2          1.3         0.2  setosa
   4 │         4.6         3.1          1.5         0.2  setosa
   5 │         5.0         3.6          1.4         0.2  setosa
   6 │         5.4         3.9          1.7         0.4  setosa
   7 │         4.6         3.4          1.4         0.3  setosa
   8 │         5.0         3.4          1.5         0.2  setosa
   9 │         4.4         2.9          1.4         0.2  setosa
  10 │         4.9         3.1          1.5         0.1  setosa
  11 │         5.4         3.7          1.5         0.2  setosa
  ⋮  │      ⋮           ⋮            ⋮           ⋮           ⋮
 141 │         6.7         3.1          5.6         2.4  virginica
 142 │         6.9         3.1          5.1         2.3  virginica
 143 │         5.8         2.7          5.1         1.9  virginica
 144 │         6.8         3.2          5.9         2.3  virginica
 145 │         6.7         3.3          5.7         2.5  virginica
 146 │         6.7         3.0          5.2         2.3  virginica
 147 │         6.3         2.5          5.0         1.9  virginica
 148 │         6.5         3.0          5.2         2.0  virginica
 149 │         6.2         3.4          5.4         2.3  virginica
 150 │         5.9         3.0          5.1         1.8  virginica
                                                   129 rows omitted

In [18]:
X = Matrix(iris[:, 1:4])

150×4 Matrix{Float64}:
 5.1  3.5  1.4  0.2
 4.9  3.0  1.4  0.2
 4.7  3.2  1.3  0.2
 4.6  3.1  1.5  0.2
 5.0  3.6  1.4  0.2
 5.4  3.9  1.7  0.4
 4.6  3.4  1.4  0.3
 5.0  3.4  1.5  0.2
 4.4  2.9  1.4  0.2
 4.9  3.1  1.5  0.1
 5.4  3.7  1.5  0.2
 4.8  3.4  1.6  0.2
 4.8  3.0  1.4  0.1
 ⋮              
 6.0  3.0  4.8  1.8
 6.9  3.1  5.4  2.1
 6.7  3.1  5.6  2.4
 6.9  3.1  5.1  2.3
 5.8  2.7  5.1  1.9
 6.8  3.2  5.9  2.3
 6.7  3.3  5.7  2.5
 6.7  3.0  5.2  2.3
 6.3  2.5  5.0  1.9
 6.5  3.0  5.2  2.0
 6.2  3.4  5.4  2.3
 5.9  3.0  5.1  1.8

In [17]:
irislabels = iris[:, 5]

150-element CategoricalArrays.CategoricalArray{String,1,UInt8}:
 "setosa"
 "setosa"
 "setosa"
 "setosa"
 "setosa"
 "setosa"
 "setosa"
 "setosa"
 "setosa"
 "setosa"
 "setosa"
 "setosa"
 "setosa"
 ⋮
 "virginica"
 "virginica"
 "virginica"
 "virginica"
 "virginica"
 "virginica"
 "virginica"
 "virginica"
 "virginica"
 "virginica"
 "virginica"
 "virginica"

In [19]:
countmap(irislabels)

Dict{CategoricalArrays.CategoricalValue{String, UInt8}, Int64} with 3 entries:
  "virginica"  => 50
  "setosa"     => 50
  "versicolor" => 50

In [6]:
?countmap

search: countmap



```
countmap(x; alg = :auto)
countmap(x::AbstractVector, w::AbstractVector{<:Real}; alg = :auto)
```

Return a dictionary mapping each unique value in `x` to its number of occurrences. A vector of weights `w` can be provided when `x` is a vector.

  * `:auto` (default): if `StatsBase.radixsort_safe(eltype(x)) == true` then use                    `:radixsort`, otherwise use `:dict`.
  * `:radixsort`:      if `radixsort_safe(eltype(x)) == true` then use the                    [radix sort](https://en.wikipedia.org/wiki/Radix_sort)                    algorithm to sort the input vector which will generally lead to                    shorter running time. However the radix sort algorithm creates a                    copy of the input vector and hence uses more RAM. Choose `:dict`                    if the amount of available RAM is a limitation.
  * `:dict`:           use `Dict`-based method which is generally slower but uses less                    RAM and is safe for any data type.


In [20]:
irislabelsmap = labelmap(irislabels)

LabelMap (with 3 labels):
[1] setosa
[2] versicolor
[3] virginica


In [21]:
y = labelencode(irislabelsmap, irislabels)

150-element Vector{Int64}:
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 ⋮
 3
 3
 3
 3
 3
 3
 3
 3
 3
 3
 3
 3

In [22]:
function perclass_splits(y, at)
    uids = unique(y)
    keepids = []
    for ui in uids
        curids = findall(y .== ui)
        rowids = randsubseq(curids, at)
        push!(keepids, rowids...)
    end
    return keepids
end

perclass_splits (generic function with 1 method)

In [10]:
?randsubseq # R의 sample 함수랑 비슷!

search: randsubseq randsubseq! RandomSub StratifiedRandomSub



```
randsubseq([rng=GLOBAL_RNG,] A, p) -> Vector
```

Return a vector consisting of a random subsequence of the given array `A`, where each element of `A` is included (in order) with independent probability `p`. (Complexity is linear in `p*length(A)`, so this function is efficient even if `p` is small and `A` is large.) Technically, this process is known as "Bernoulli sampling" of `A`.

# Examples

```jldoctest
julia> rng = MersenneTwister(1234);

julia> randsubseq(rng, 1:8, 0.3)
2-element Vector{Int64}:
 7
 8
```


In [23]:
using Random
Random.seed!(123)

MersenneTwister(123)

In [24]:
trainids = perclass_splits(y, 0.7)
testids = setdiff(1:length(y), trainids)

50-element Vector{Int64}:
   1
   2
  13
  21
  24
  26
  28
  30
  32
  34
  37
  38
  44
   ⋮
 107
 108
 109
 115
 128
 133
 134
 137
 141
 144
 146
 148

- 예측값이 연속적인 값을 경우 사용하기 위한 클래스 지정 함수 작성

In [25]:
assign_class(predictedvalue) = argmin(abs.(predictedvalue .- [1, 2, 3]))

assign_class (generic function with 1 method)

## 1. Lasso

- Lasso, Ridge, ElasticNet은 GLMNet.jl 패키지 사용

> (참고) GLMNet.jl 패키지는 R의 glmnet 패키지와 동일하다고 볼 수 있음 
> glmnet is an R package by Jerome Friedman, Trevor Hastie, Rob Tibshirani that fits entire Lasso or ElasticNet regularization paths for linear, logistic, multinomial, and Cox models using cyclic coordinate descent. This Julia package wraps the Fortran code from glmnet.

> - https://github.com/JuliaStats/GLMNet.jl

>* https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Lasso.html
>* https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Ridge.html
>* https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.ElasticNet.html

In [27]:
?glmnet

search: glmnet glmnet! glmnetcv GLMNet GLMNetPath GLMNetCrossValidation



No documentation found.

`GLMNet.glmnet` is a `Function`.

```
# 16 methods for generic function "glmnet":
[1] glmnet(X::SparseArrays.SparseMatrixCSC, y::AbstractVector{var"#s89"} where var"#s89"<:Number) in GLMNet at C:\Users\user\.julia\packages\GLMNet\uXUb5\src\GLMNet.jl:494
[2] glmnet(X::SparseArrays.SparseMatrixCSC, y::AbstractVector{var"#s88"} where var"#s88"<:Number, family::Distributions.Distribution; kw...) in GLMNet at C:\Users\user\.julia\packages\GLMNet\uXUb5\src\GLMNet.jl:494
[3] glmnet(X::SparseArrays.SparseMatrixCSC, y::AbstractMatrix{T} where T, family::Distributions.Binomial; kw...) in GLMNet at C:\Users\user\.julia\packages\GLMNet\uXUb5\src\GLMNet.jl:498
[4] glmnet(X::Matrix{Float64}, y::Vector{Float64}) in GLMNet at C:\Users\user\.julia\packages\GLMNet\uXUb5\src\GLMNet.jl:490
[5] glmnet(X::AbstractMatrix{T} where T, time::AbstractVector{T} where T, status::AbstractVector{T} where T) in GLMNet at C:\Users\user\.julia\packages\GLMNet\uXUb5\src\CoxNet.jl:151
[6] glmnet(X::AbstractMatrix{T} where T, time::AbstractVector{T} where T, status::AbstractVector{T} where T, family::CoxPH; kw...) in GLMNet at C:\Users\user\.julia\packages\GLMNet\uXUb5\src\CoxNet.jl:151
[7] glmnet(X::Matrix{Float64}, y::Vector{Float64}, family::Distributions.Distribution; kw...) in GLMNet at C:\Users\user\.julia\packages\GLMNet\uXUb5\src\GLMNet.jl:490
[8] glmnet(X::Matrix{Float64}, y::Matrix{Float64}, family::Distributions.Binomial; kw...) in GLMNet at C:\Users\user\.julia\packages\GLMNet\uXUb5\src\GLMNet.jl:496
[9] glmnet(X::Matrix{T} where T, y::Matrix{T} where T, family::Distributions.Binomial; kw...) in GLMNet at C:\Users\user\.julia\packages\GLMNet\uXUb5\src\GLMNet.jl:500
[10] glmnet(X::Matrix{Float64}, y::Matrix{Float64}, family::Distributions.Multinomial; kw...) in GLMNet at C:\Users\user\.julia\packages\GLMNet\uXUb5\src\Multinomial.jl:185
[11] glmnet(X::AbstractMatrix{T} where T, y::AbstractMatrix{T} where T, family::Distributions.Multinomial; kw...) in GLMNet at C:\Users\user\.julia\packages\GLMNet\uXUb5\src\Multinomial.jl:188
[12] glmnet(X::Matrix{Float64}, y::Matrix{Float64}, family::CoxPH; kw...) in GLMNet at C:\Users\user\.julia\packages\GLMNet\uXUb5\src\CoxNet.jl:145
[13] glmnet(X::AbstractMatrix{T} where T, y::AbstractVector{var"#s89"} where var"#s89"<:Number) in GLMNet at C:\Users\user\.julia\packages\GLMNet\uXUb5\src\GLMNet.jl:492
[14] glmnet(X::AbstractMatrix{T} where T, y::AbstractVector{var"#s88"} where var"#s88"<:Number, family::Distributions.Distribution; kw...) in GLMNet at C:\Users\user\.julia\packages\GLMNet\uXUb5\src\GLMNet.jl:492
[15] glmnet(X::AbstractMatrix{T} where T, y::AbstractMatrix{T} where T, family::CoxPH; kw...) in GLMNet at C:\Users\user\.julia\packages\GLMNet\uXUb5\src\CoxNet.jl:148
[16] glmnet(X::AbstractMatrix{T} where T, y; kw...) in GLMNet at C:\Users\user\.julia\packages\GLMNet\uXUb5\src\Multinomial.jl:191
```


### Fitting models

glmnet has two required parameters: the m x n predictor matrix X and the dependent variable y. It additionally accepts an optional third argument, family, which can be used to specify a generalized linear model. Currently, only Normal() (least squares, default), Binomial() (logistic), and Poisson() are supported, although the glmnet Fortran code also implements a Cox model. For logistic models, y is a m x 2 matrix, where the first column is the count of negative responses for each row in X and the second column is the count of positive responses. For all other models, y is a vector.

- [glmnet] also accepts many optional parameters, described below:

- weights: A vector of weights for each sample of the same size as y.

- alpha: The tradeoff between lasso and ridge regression. This defaults to 1.0, which specifies a lasso model.

penalty_factor: A vector of length n of penalties for each predictor in X. This defaults to all ones, which weights each predictor 
equally. To specify that a predictor should be unpenalized, set the corresponding entry to zero.

constraints: An n x 2 matrix specifying lower bounds (first column) and upper bounds (second column) on each predictor. By default, this is [-Inf Inf] for each predictor in X.

dfmax: The maximum number of predictors in the largest model.

pmax: The maximum number of predictors in any model.

nlambda: The number of values of λ along the path to consider.

lambda_min_ratio: The smallest λ value to consider, as a ratio of the value of λ that gives the null model (i.e., the model with only an intercept). If the number of observations exceeds the number of variables, this defaults to 0.0001, otherwise 0.01.

lambda: The λ values to consider. By default, this is determined from nlambda and lambda_min_ratio.

tol: Convergence criterion. Defaults to 1e-7.

standardize: Whether to standardize predictors so that they are in the same units. Defaults to true. Beta values are always presented on the original scale.

intercept: Whether to fit an intercept term. The intercept is always unpenalized. Defaults to true.

maxit: The maximum number of iterations of the cyclic coordinate descent algorithm. If convergence is not achieved, a warning is returned.

In [37]:
path_1 = glmnet(X[trainids, :], y[trainids]) #alpha(sklearn에서의 L1 ration)의 default 값이 1 이므로 

Least Squares GLMNet Solution Path (73 solutions for 4 predictors in 1135 passes):
───────────────────────────────
      df   pct_dev            λ
───────────────────────────────
 [1]   0  0.0       0.808902
 [2]   1  0.15649   0.737042
 [3]   1  0.286411  0.671565
 [4]   1  0.394274  0.611905
 [5]   2  0.484985  0.557545
 [6]   2  0.560524  0.508014
 [7]   2  0.623229  0.462884
 [8]   2  0.675286  0.421762
 [9]   2  0.718504  0.384294
[10]   2  0.754383  0.350154
[11]   2  0.784176  0.319048
[12]   2  0.808906  0.290704
[13]   2  0.829435  0.264879
[14]   2  0.846478  0.241348
[15]   2  0.860627  0.219907
[16]   2  0.872374  0.200371
[17]   2  0.882125  0.182571
[18]   2  0.890221  0.166352
[19]   2  0.896942  0.151574
[20]   2  0.902521  0.138108
[21]   2  0.907153  0.125839
[22]   2  0.910998  0.11466
[23]   2  0.91419   0.104474
[24]   2  0.91684   0.0951926
[25]   2  0.91904   0.0867359
[26]   2  0.920865  0.0790306
[27]   2  0.922381  0.0720097
[28]   3  0.924062  0.0656126
[29] 

In [38]:
path_1.a0

73-element Vector{Float64}:
 1.9900000000000015
 1.8804564159276511
 1.7806443819495192
 1.6896993739765123
 1.594378610353271
 1.5049382090408558
 1.4235266804776043
 1.3493588117020523
 1.2817820990128395
 1.2202096196732066
 1.163980294143869
 1.1128389377503884
 1.066257046651712
 ⋮
 1.1790015574826218
 1.187517310459731
 1.1951937031552216
 1.2021553369848859
 1.208469976169066
 1.214382692177558
 1.2196578722491997
 1.2244100262558657
 1.228690967166628
 1.2327576673244245
 1.2363286553876363
 1.2397249463668616

In [44]:
coef(path_1)

LoadError: UndefVarError: coef not defined

In [31]:
cv = glmnetcv(X[trainids, :], y[trainids])

Least Squares GLMNet Cross Validation
73 models for 4 predictors in 10 folds
Best λ 0.001 (mean loss 0.051, std 0.007)

최적 람다값을 추출

In [32]:
# choose the best lambda to predict with.
path = glmnet(X[trainids, :], y[trainids])
cv = glmnetcv(X[trainids, :], y[trainids])
mylambda = path.lambda[argmin(cv.meanloss)]

print(mylambda)

0.012294594776065372

In [33]:
path = glmnet(X[trainids, :], y[trainids], lambda = [mylambda])

Least Squares GLMNet Solution Path (1 solutions for 4 predictors in 83 passes):
────────────────────────────
     df   pct_dev          λ
────────────────────────────
[1]   3  0.932702  0.0122946
────────────────────────────

In [34]:
path.lambda

1-element Vector{Float64}:
 0.012294594776065372

$names
 [1] "a0"        "beta"      "dfmat"     "df"        "dim"       "lambda"    "dev.ratio" "nulldev"   "npasses"  
[10] "jerr"      "offset"    "call"      "nobs"  

In [35]:
path.a0

1-element Vector{Float64}:
 0.9483636076467223

In [46]:
path.betas # coef(path)

4×1 CompressedPredictorMatrix:
  0.0
 -0.09543015992081726
  0.1440166266049501
  0.6748624842387528

In [52]:
typeof(path)

GLMNetPath{Distributions.Normal{Float64}, Vector{Float64}, CompressedPredictorMatrix}

In [53]:
terms(path)

LoadError: UndefVarError: terms not defined

In [50]:
convert(Matrix, path.betas)

4×1 Matrix{Float64}:
  0.0
 -0.09543015992081726
  0.1440166266049501
  0.6748624842387528

In [51]:
convert(Matrix, path_1.betas)

4×73 Matrix{Float64}:
 0.0  0.0        0.0       0.0       …  -0.12822    -0.129945   -0.131617
 0.0  0.0        0.0       0.0          -0.0324123  -0.0314856  -0.0305667
 0.0  0.0        0.0       0.0           0.236176    0.237471    0.238729
 0.0  0.0922861  0.176374  0.252991      0.61588     0.614923    0.613983

In [40]:
q = X[testids, :];
predictions_lasso = GLMNet.predict(path, q)

50×1 Matrix{Float64}:
 0.9509538220185427
 0.9986689019789514
 0.9311826535550761
 1.0037018259921093
 1.215703587255817
 1.0274722272999413
 0.9653554846790378
 1.0083861953157778
 1.10987099751887
 0.8841527100739706
 0.9365521593580477
 0.8739245576025857
 1.2497021410350337
 ⋮
 2.5051292507728347
 2.793673363117293
 2.759837113783145
 3.035313917726686
 2.5825070698782815
 2.972349734181411
 2.427937681911809
 3.050064135076671
 3.0786931830529163
 3.0448689066184444
 2.9631432999791425
 2.7606845547075167

In [40]:
pred_class_lasso = assign_class.(predictions_lasso)

50×1 Matrix{Int64}:
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 ⋮
 3
 3
 3
 3
 3
 3
 2
 3
 3
 3
 3
 3

In [41]:
findaccuracy(pred_class_lasso, y[testids])

0.96

## 2. Ridge
- We will use the same function but set alpha to zero.

In [42]:
# choose the best lambda to predict with
path = glmnet(X[trainids, :], y[trainids], alpha = 0); 
# ;를 붙이면 결과 출력 없이 진행 됨
cv = glmnetcv(X[trainids, :], y[trainids], alpha = 0)
mylambda = path.lambda[argmin(cv.meanloss)]
path = glmnet(X[trainids, :], y[trainids], alpha = 0, lambda = [mylambda]);

q = X[testids, :];
predictions_ridge = GLMNet.predict(path, q)
pred_class_ridge = assign_class.(predictions_ridge)
findaccuracy(pred_class_ridge, y[testids])

0.94

## 3. Elastic Net
- We will use the same function but set alpha to 0.5 (it's the combination of lasso and ridge).

In [45]:
# choose the best lambda to predict with.
path = glmnet(X[trainids, :], y[trainids], alpha = 0.5);
cv = glmnetcv(X[trainids, :], y[trainids], alpha = 0.5)
mylambda = path.lambda[argmin(cv.meanloss)]
path = glmnet(X[trainids, :], y[trainids], alpha = 0.5, lambda = [mylambda]);
q = X[testids, :];
predictions_EN = GLMNet.predict(path, q)
pred_class_EN = assign_class.(predictions_EN)
findaccuracy(pred_class_EN, y[testids])

0.94

## 4. Decision Tree
- DecisionTree 패키지 사용

> Julia implementation of Decision Tree (CART) and Random Forest algorithms

> Available via:
> * AutoMLPipeline.jl - create complex ML pipeline structures using simple expressions
    - https://github.com/IBM/AutoMLPipeline.jl
> * CombineML.jl - a heterogeneous ensemble learning package
    - https://github.com/ppalmes/CombineML.jl
> * MLJ.jl - a machine learning framework for Julia
    - https://alan-turing-institute.github.io/MLJ.jl/dev/
    - https://github.com/alan-turing-institute/MLJ.jl
> * ScikitLearn.jl - Julia implementation of the scikit-learn API
    - https://github.com/cstjean/ScikitLearn.jl

In [46]:
model = DecisionTreeClassifier(max_depth = 2)

DecisionTreeClassifier
max_depth:                2
min_samples_leaf:         1
min_samples_split:        2
min_purity_increase:      0.0
pruning_purity_threshold: 1.0
n_subfeatures:            0
classes:                  nothing
root:                     nothing

In [47]:
DecisionTree.fit!(model, X[trainids, :], y[trainids])

DecisionTreeClassifier
max_depth:                2
min_samples_leaf:         1
min_samples_split:        2
min_purity_increase:      0.0
pruning_purity_threshold: 1.0
n_subfeatures:            0
classes:                  [1, 2, 3]
root:                     Decision Tree
Leaves: 3
Depth:  2

In [49]:
q = X[testids, :];
predictions_DT = DecisionTree.predict(model, q)

50-element Vector{Int64}:
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 ⋮
 2
 3
 3
 3
 3
 3
 3
 3
 3
 3
 3
 3

In [50]:
findaccuracy(predictions_DT, y[testids])

0.92

## 5. Random Forests

- The RandomForestClassifier is available through the DecisionTree package as well.

In [51]:
model = RandomForestClassifier(n_trees = 20)

RandomForestClassifier
n_trees:             20
n_subfeatures:       -1
partial_sampling:    0.7
max_depth:           -1
min_samples_leaf:    1
min_samples_split:   2
min_purity_increase: 0.0
classes:             nothing
ensemble:            nothing

In [52]:
DecisionTree.fit!(model, X[trainids, :], y[trainids])

RandomForestClassifier
n_trees:             20
n_subfeatures:       -1
partial_sampling:    0.7
max_depth:           -1
min_samples_leaf:    1
min_samples_split:   2
min_purity_increase: 0.0
classes:             [1, 2, 3]
ensemble:            Ensemble of Decision Trees
Trees:      20
Avg Leaves: 5.8
Avg Depth:  4.2

In [53]:
q = X[testids, :];
predictions_RF = DecisionTree.predict(model, q)

50-element Vector{Int64}:
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 ⋮
 2
 3
 3
 3
 3
 3
 2
 3
 3
 3
 3
 3

In [54]:
findaccuracy(predictions_RF, y[testids])

0.94

## 6. Using a Nearest Neighbor method
- We will use the NearestNeighbors package here
> * NearestNeighbors.jl is a package written in Julia to perform high performance nearest neighbor searches in arbitrarily high dimensions.
>   - https://github.com/KristofferC/NearestNeighbors.jl
>   - 줄리아로 모든 함수가 짜여 있음 

In [55]:
Xtrain = X[trainids, :]
ytrain = y[trainids]
kdtree = KDTree(Xtrain')

KDTree{StaticArrays.SVector{4, Float64}, Euclidean, Float64}
  Number of points: 100
  Dimensions: 4
  Metric: Euclidean(0.0)
  Reordered: true

- https://blog.naver.com/laonple/221207919855
KDTree 설명 참조

In [56]:
queries = X[testids, :]

50×4 Matrix{Float64}:
 5.1  3.5  1.4  0.2
 4.9  3.0  1.4  0.2
 4.8  3.0  1.4  0.1
 5.4  3.4  1.7  0.2
 5.1  3.3  1.7  0.5
 5.0  3.0  1.6  0.2
 5.2  3.5  1.5  0.2
 4.7  3.2  1.6  0.2
 5.4  3.4  1.5  0.4
 5.5  4.2  1.4  0.2
 5.5  3.5  1.3  0.2
 4.9  3.6  1.4  0.1
 5.0  3.5  1.6  0.6
 ⋮              
 4.9  2.5  4.5  1.7
 7.3  2.9  6.3  1.8
 6.7  2.5  5.8  1.8
 5.8  2.8  5.1  2.4
 6.1  3.0  4.9  1.8
 6.4  2.8  5.6  2.2
 6.3  2.8  5.1  1.5
 6.3  3.4  5.6  2.4
 6.7  3.1  5.6  2.4
 6.8  3.2  5.9  2.3
 6.7  3.0  5.2  2.3
 6.5  3.0  5.2  2.0

In [64]:
idxs, dists = knn(kdtree, queries', 3, true)

([[15, 3, 28], [25, 33, 8], [8, 33, 25], [22, 9, 28], [21, 28, 6], [25, 8, 23], [22, 28, 15], [23, 2, 10], [22, 15, 9], [24, 13, 14]  …  [86, 75, 71], [80, 67, 96], [93, 85, 100], [86, 71, 72], [57, 82, 85], [99, 74, 66], [97, 79, 72], [79, 83, 97], [95, 94, 72], [70, 71, 75]], [[0.09999999999999998, 0.1414213562373093, 0.14142135623730964], [0.14142135623730964, 0.14142135623730986, 0.17320508075688784], [0.17320508075688815, 0.19999999999999998, 0.20000000000000037], [0.36055512754639907, 0.3605551275463991, 0.3605551275463995], [0.1999999999999998, 0.3741657386773941, 0.3872983346207416], [0.17320508075688762, 0.19999999999999993, 0.22360679774997916], [0.14142135623730964, 0.14142135623730995, 0.17320508075688806], [0.1414213562373093, 0.17320508075688815, 0.22360679774997858], [0.30000000000000016, 0.3464101615137761, 0.3605551275463992], [0.3464101615137755, 0.3605551275463992, 0.38729833462074176]  …  [0.5567764362830021, 0.6164414002968976, 0.6244997998398398], [0.4898979485566

In [67]:
idxs

50-element Vector{Vector{Int64}}:
 [15, 3, 28]
 [25, 33, 8]
 [8, 33, 25]
 [22, 9, 28]
 [21, 28, 6]
 [25, 8, 23]
 [22, 28, 15]
 [23, 2, 10]
 [22, 15, 9]
 [24, 13, 14]
 [9, 22, 15]
 [3, 29, 6]
 [21, 18, 15]
 ⋮
 [45, 59, 62]
 [88, 84, 68]
 [86, 75, 71]
 [80, 67, 96]
 [93, 85, 100]
 [86, 71, 72]
 [57, 82, 85]
 [99, 74, 66]
 [97, 79, 72]
 [79, 83, 97]
 [95, 94, 72]
 [70, 71, 75]

In [68]:
digits

digits (generic function with 2 methods)

In [65]:
c = ytrain[hcat(idxs...)]
possible_labels = map(i -> counter(c[:, i]), 1:size(c, 2))

50-element Vector{Accumulator{Int64, Int64}}:
 Accumulator(1 => 3)
 Accumulator(1 => 3)
 Accumulator(1 => 3)
 Accumulator(1 => 3)
 Accumulator(1 => 3)
 Accumulator(1 => 3)
 Accumulator(1 => 3)
 Accumulator(1 => 3)
 Accumulator(1 => 3)
 Accumulator(1 => 3)
 Accumulator(1 => 3)
 Accumulator(1 => 3)
 Accumulator(1 => 3)
 ⋮
 Accumulator(2 => 3)
 Accumulator(3 => 3)
 Accumulator(3 => 3)
 Accumulator(3 => 3)
 Accumulator(3 => 3)
 Accumulator(3 => 3)
 Accumulator(2 => 1, 3 => 2)
 Accumulator(3 => 3)
 Accumulator(3 => 3)
 Accumulator(3 => 3)
 Accumulator(3 => 3)
 Accumulator(3 => 3)

In [108]:
print(DataFrame(possible_labels))

50×1 DataFrame
 Row │ map              
     │ Dict…            
─────┼──────────────────
   1 │ Dict(1=>3)
   2 │ Dict(1=>3)
   3 │ Dict(1=>3)
   4 │ Dict(1=>3)
   5 │ Dict(1=>3)
   6 │ Dict(1=>3)
   7 │ Dict(1=>3)
   8 │ Dict(1=>3)
   9 │ Dict(1=>3)
  10 │ Dict(1=>3)
  11 │ Dict(1=>3)
  12 │ Dict(1=>3)
  13 │ Dict(1=>3)
  14 │ Dict(1=>3)
  15 │ Dict(2=>3)
  16 │ Dict(2=>3)
  17 │ Dict(2=>3)
  18 │ Dict(2=>3)
  19 │ Dict(2=>3)
  20 │ Dict(2=>3)
  21 │ Dict(2=>1, 3=>2)
  22 │ Dict(2=>3)
  23 │ Dict(2=>3)
  24 │ Dict(2=>2, 3=>1)
  25 │ Dict(2=>3)
  26 │ Dict(2=>3)
  27 │ Dict(2=>3)
  28 │ Dict(2=>3)
  29 │ Dict(2=>3)
  30 │ Dict(2=>3)
  31 │ Dict(2=>3)
  32 │ Dict(2=>3)
  33 │ Dict(2=>3)
  34 │ Dict(2=>3)
  35 │ Dict(2=>3)
  36 │ Dict(3=>3)
  37 │ Dict(3=>3)
  38 │ Dict(3=>3)
  39 │ Dict(2=>3)
  40 │ Dict(3=>3)
  41 │ Dict(3=>3)
  42 │ Dict(3=>3)
  43 │ Dict(3=>3)
  44 │ Dict(3=>3)
  45 │ Dict(2=>1, 3=>2)
  46 │ Dict(3=>3)
  47 │ Dict(3=>3)
  48 │ Dict(3=>3)
  49 │ Dict(3=>3)
  50 │ Dic

In [111]:
possible_labels[21]

Accumulator{Int64, Int64} with 2 entries:
  2 => 1
  3 => 2

In [112]:
argmax(possible_labels[21])

3

In [113]:
typeof(argmax(possible_labels[21]))

Int64

In [114]:
predictions_NN = map(i -> argmax(possible_labels[i]), 1:size(c,2))
# map 함수는 apply 계열 함수

50-element Vector{Int64}:
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 ⋮
 2
 3
 3
 3
 3
 3
 3
 3
 3
 3
 3
 3

In [118]:
print(DataFrame(possible_labels))
print("\n")
print(predictions_NN)
print("\n")
print(y[testids])

50×1 DataFrame
 Row │ map              
     │ Dict…            
─────┼──────────────────
   1 │ Dict(1=>3)
   2 │ Dict(1=>3)
   3 │ Dict(1=>3)
   4 │ Dict(1=>3)
   5 │ Dict(1=>3)
   6 │ Dict(1=>3)
   7 │ Dict(1=>3)
   8 │ Dict(1=>3)
   9 │ Dict(1=>3)
  10 │ Dict(1=>3)
  11 │ Dict(1=>3)
  12 │ Dict(1=>3)
  13 │ Dict(1=>3)
  14 │ Dict(1=>3)
  15 │ Dict(2=>3)
  16 │ Dict(2=>3)
  17 │ Dict(2=>3)
  18 │ Dict(2=>3)
  19 │ Dict(2=>3)
  20 │ Dict(2=>3)
  21 │ Dict(2=>1, 3=>2)
  22 │ Dict(2=>3)
  23 │ Dict(2=>3)
  24 │ Dict(2=>2, 3=>1)
  25 │ Dict(2=>3)
  26 │ Dict(2=>3)
  27 │ Dict(2=>3)
  28 │ Dict(2=>3)
  29 │ Dict(2=>3)
  30 │ Dict(2=>3)
  31 │ Dict(2=>3)
  32 │ Dict(2=>3)
  33 │ Dict(2=>3)
  34 │ Dict(2=>3)
  35 │ Dict(2=>3)
  36 │ Dict(3=>3)
  37 │ Dict(3=>3)
  38 │ Dict(3=>3)
  39 │ Dict(2=>3)
  40 │ Dict(3=>3)
  41 │ Dict(3=>3)
  42 │ Dict(3=>3)
  43 │ Dict(3=>3)
  44 │ Dict(3=>3)
  45 │ Dict(2=>1, 3=>2)
  46 │ Dict(3=>3)
  47 │ Dict(3=>3)
  48 │ Dict(3=>3)
  49 │ Dict(3=>3)
  50 │ Dic

In [66]:
# 원코드의 함수  -> 에러 나옴
predictions_NN = map(i->parse(Int,string(argmax(DataFrame(possible_labels[i])[1,:]))),1:size(c,2))
findaccuracy(predictions_NN,y[testids])

LoadError: ArgumentError: All column names must be either Symbols or strings (mixing is not allowed)

In [117]:
findaccuracy(predictions_NN,y[testids])

0.96

In [125]:
temp_df = DataFrame("pred" => predictions_NN, "real" => y[testids], "diff" =>  predictions_NN-y[testids] )

50×3 DataFrame
 Row │ pred   real   diff  
     │ Int64  Int64  Int64 
─────┼─────────────────────
   1 │     1      1      0
   2 │     1      1      0
   3 │     1      1      0
   4 │     1      1      0
   5 │     1      1      0
   6 │     1      1      0
   7 │     1      1      0
   8 │     1      1      0
   9 │     1      1      0
  10 │     1      1      0
  11 │     1      1      0
  ⋮  │   ⋮      ⋮      ⋮
  41 │     3      3      0
  42 │     3      3      0
  43 │     3      3      0
  44 │     3      3      0
  45 │     3      3      0
  46 │     3      3      0
  47 │     3      3      0
  48 │     3      3      0
  49 │     3      3      0
  50 │     3      3      0
            29 rows omitted

In [126]:
print(temp_df)

50×3 DataFrame
 Row │ pred   real   diff  
     │ Int64  Int64  Int64 
─────┼─────────────────────
   1 │     1      1      0
   2 │     1      1      0
   3 │     1      1      0
   4 │     1      1      0
   5 │     1      1      0
   6 │     1      1      0
   7 │     1      1      0
   8 │     1      1      0
   9 │     1      1      0
  10 │     1      1      0
  11 │     1      1      0
  12 │     1      1      0
  13 │     1      1      0
  14 │     1      1      0
  15 │     2      2      0
  16 │     2      2      0
  17 │     2      2      0
  18 │     2      2      0
  19 │     2      2      0
  20 │     2      2      0
  21 │     3      2      1
  22 │     2      2      0
  23 │     2      2      0
  24 │     2      2      0
  25 │     2      2      0
  26 │     2      2      0
  27 │     2      2      0
  28 │     2      2      0
  29 │     2      2      0
  30 │     2      2      0
  31 │     2      2      0
  32 │     2      2      0
  33 │     2      2      0
  34 │    

- 검증 완료

## 7. SVM(Support Vector Machines)
- We will use the `LIBSVM` package here

> https://github.com/JuliaML/LIBSVM.jl


> https://www.csie.ntu.edu.tw/~cjlin/libsvm/


In [127]:
Xtrain = X[trainids, :]
ytrain = y[trainids]

100-element Vector{Int64}:
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 ⋮
 3
 3
 3
 3
 3
 3
 3
 3
 3
 3
 3
 3

In [128]:
model = svmtrain(Xtrain', ytrain)

LIBSVM.SVM{Int64}(SVC, LIBSVM.Kernel.RadialBasis, nothing, 4, 3, [1, 2, 3], Int32[1, 2, 3], Float64[], Int32[], LIBSVM.SupportVectors{Int64, Float64}(36, Int32[6, 14, 16], [1, 1, 1, 1, 1, 1, 2, 2, 2, 2  …  3, 3, 3, 3, 3, 3, 3, 3, 3, 3], [4.3 5.7 … 6.3 5.9; 3.0 4.4 … 2.5 3.0; 1.1 1.5 … 5.0 5.1; 0.1 0.4 … 1.9 1.8], Int32[11, 13, 16, 20, 30, 32, 37, 39, 41, 42  …  82, 85, 87, 89, 90, 93, 95, 96, 98, 100], LIBSVM.SVMNode[LIBSVM.SVMNode(1, 4.3), LIBSVM.SVMNode(1, 5.7), LIBSVM.SVMNode(1, 5.7), LIBSVM.SVMNode(1, 4.8), LIBSVM.SVMNode(1, 4.5), LIBSVM.SVMNode(1, 5.1), LIBSVM.SVMNode(1, 7.0), LIBSVM.SVMNode(1, 6.9), LIBSVM.SVMNode(1, 6.5), LIBSVM.SVMNode(1, 6.3)  …  LIBSVM.SVMNode(1, 6.3), LIBSVM.SVMNode(1, 6.2), LIBSVM.SVMNode(1, 7.2), LIBSVM.SVMNode(1, 7.9), LIBSVM.SVMNode(1, 6.1), LIBSVM.SVMNode(1, 6.0), LIBSVM.SVMNode(1, 6.9), LIBSVM.SVMNode(1, 5.8), LIBSVM.SVMNode(1, 6.3), LIBSVM.SVMNode(1, 5.9)]), 0.0, [0.0 0.04328020851343606; 0.43954679567868465 0.9047809464113701; … ; -0.0 -1.0; -0.0 -1.

In [129]:
predictions_SVM, dicistion_values = svmpredict(model, X[testids, :]')

([1, 1, 1, 1, 1, 1, 1, 1, 1, 1  …  3, 3, 3, 3, 3, 3, 3, 3, 3, 3], [1.238486216673677 1.1816741085391615 … -0.7851730822247001 -0.8892808489546852; 1.133911522560622 1.121930201818705 … -1.062793861648126 -1.1017855054534904; 0.09504587304145165 0.11448678438948887 … -1.2626302256411652 -0.9533465403643183])

In [130]:
findaccuracy(predictions_SVM, y[testids])

0.98

In [131]:
overall_accuracies = zeros(7)
methods = ["lasso","ridge","EN", "DT", "RF","kNN", "SVM"]
ytest = y[testids]
overall_accuracies[1] = findaccuracy(pred_class_lasso,ytest)
overall_accuracies[2] = findaccuracy(pred_class_ridge,ytest)
overall_accuracies[3] = findaccuracy(pred_class_EN,ytest)
overall_accuracies[4] = findaccuracy(predictions_DT,ytest)
overall_accuracies[5] = findaccuracy(predictions_RF,ytest)
overall_accuracies[6] = findaccuracy(predictions_NN,ytest)
overall_accuracies[7] = findaccuracy(predictions_SVM,ytest)
hcat(methods, overall_accuracies)

7×2 Matrix{Any}:
 "lasso"  0.96
 "ridge"  0.94
 "EN"     0.94
 "DT"     0.92
 "RF"     0.94
 "kNN"    0.96
 "SVM"    0.98

# Finally...
After finishing this notebook, you should be able to:
- [ ] split your data into training and testing data to test the effectiveness of a certain method
- [ ] apply a simple accuracy function to test the effectiveness of a certain method
- [ ] run multiple classification algorithms:
    - [ ] LASSO
    - [ ] Ridge
    - [ ] ElasticNet
    - [ ] Decision Tree
    - [ ] Random Forest
    - [ ] Nearest Neighbors
    - [ ] Support Vector Machines